USERNAME = "boroninm@gmail.com"
PASSWORD = "23MBoronin#"
BU_LOGIN_URL = "https://bostad.uppsala.se/logga-in-mina-sidor/"
BU_URL = 'https://bostad.uppsala.se/lediga-bostader/'
DB_TABLE='rentals'
DB_SCHEMA='housing'
DB_HOST='localhost'
DB_PORT=3306
DB_USER='bot'
DB_PASS="1"
BOSTAD_LINK = "https://bostad.uppsala.se"
TIME_CONST = 62135604000