USERNAME = "boroninm@gmail.com"
PASSWORD = "23MBoronin#"
BU_LOGIN_URL = "https://bostad.uppsala.se/logga-in-mina-sidor/"
BU_URL = 'https://bostad.uppsala.se/lediga-bostader/'
DB_TABLE='rentals'
USER_TABLE='users'
DB_SCHEMA='housing'
DB_HOST='localhost'
DB_PORT=3306
DB_USER='bot'
DB_PASS="1"
BOSTAD_LINK = "https://bostad.uppsala.se"
TIME_CONST = 62135604000
BOT_TOKEN = "899854285:AAE2BNcc9i0N_usGmlT23cxSIDxe54o6KJs"
MIN_RENT = 0
MAX_RENT = 0
ROOMS = 0
DISTRICT = ""